const assert = require("assert");
const fs = require("fs");
const path = require("path");

const source = fs.readFileSync(path.join(__dirname, "../../src/app/renderer/dm-screen/src/main.jsx"), "utf8");

assert.match(source, /function shouldOfferBoardNoteSave\(note\)/);
assert.match(source, /function monsterNoteHasPersistentEdits\(note\)/);
assert.match(source, /note\.monsterCustom \|\| String\(note\.titleOverride \|\| ""\)\.trim\(\)/);
assert.match(source, /normalizeMonsterTextNotes\(note\.monsterTextNotes\)\.length > 0/);
assert.match(source, /function createSavedBoardNote\(note,/);
assert.match(source, /function mergeSavedBoardNotes\(currentNotes, savedNotes\)/);
assert.match(source, /function SavedBoardNameConflictModal\(/);
assert.match(source, /function continuePendingNotesSave\(plan, requestedName = "", overwrite = false\)/);
assert.match(source, /normalizeSearch\(entry\.title\) === normalizeSearch\(title\)/);
assert.match(source, /savedBoardNoteId/);
assert.match(source, /function restoreSavedBoardNote\(savedNote, index = 0\)/);
assert.match(source, /savedNotes: \[\]/);
assert.match(source, /parsed\.savedNotes\.map\(restoreSavedBoardNote\)\.filter\(Boolean\)/);
assert.match(source, /saveDmBoardState\(notes, view, savedNotes = \[\]\)/);
assert.match(source, /function requestNoteClose\(noteId, closeGroup\)/);
assert.match(source, /function tokenRemovalSaveCandidates\(entry, tokens\)/);
assert.match(source, /function removeMapTokens\(mapNoteId, pageId, tokenIds, savedNoteIds = new Map\(\)\)/);
assert.match(source, /function deleteSavedBoardNote\(savedNoteId\)/);
assert.match(source, /function pickTokenImportFiles\(\)/);
assert.match(source, /function addTokenImportFiles\(event\)/);
assert.match(source, /function confirmTokenImport\(image\)/);
assert.match(source, /aria-label="Importar imágenes de token"/);
assert.match(source, /contextMenuOpenGroups\.homebrew/);
assert.match(source, /<span>Homebrew<\/span>/);
assert.match(source, /function linkedMapTokenExistsInCollection\(note, notes\)/);
assert.match(source, /shouldOfferBoardNoteSave\(note\) && !linkedMapTokenExistsInCollection\(note, notes\)/);
assert.match(source, /function openSavedBoardNotes\(\)/);
assert.match(source, /<span>Load homebrew<\/span>/);
assert.match(source, /function SavedBoardNotesModal\(/);
assert.match(source, /const \[activeTab, setActiveTab\] = useState\("monster"\)/);
assert.match(source, /\["item", "Items"\]/);
assert.match(source, /\["monster", "Monsters"\]/);
assert.match(source, /\["spell", "Spells"\]/);
assert.match(source, /Buscar \{tabs\.find/);

console.log("DM note archive wiring verified.");
